apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cahoots
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: developer
  namespace: cahoots
spec:
  selector:
    app: developer
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: tester
  namespace: cahoots
spec:
  selector:
    app: tester
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ux-designer
  namespace: cahoots
spec:
  selector:
    app: ux-designer
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: project-manager
  namespace: cahoots
spec:
  selector:
    app: project-manager
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: context-manager
  namespace: cahoots
spec:
  selector:
    app: context-manager
  ports:
  - port: 8000
    targetPort: 8000 