[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cahoots-agents"
version = "0.1.0"
description = "AI agents for Cahoots"
requires-python = ">=3.9"
dependencies = [
    "cahoots-core>=0.1.0",
    "cahoots-events>=0.1.0",
    "cahoots-context>=0.1.0",
    "cahoots-service>=0.1.0",
    "openai>=1.0.0",
    "anthropic>=0.5.0",
    "ast-comments>=1.0.0",
    "astroid>=3.0.0",
    "pylint>=3.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0",
    "pytest-mock>=3.11.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=src --cov-report=term-missing"
asyncio_mode = "strict"

[tool.poetry]
name = "cahoots-agents"
version = "0.1.0"
description = "AI Agents for Cahoots"
authors = ["Cahoots Team"]
