---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cahoots-config
data:
  default.yaml: |
    # Environment
    env: production  # Override for production
    debug: false
    log_level: INFO

    # Redis Configuration
    redis:
      host: redis-service  # Use k8s service name
      port: 6379
      db: 0
      cluster_mode: false

    # Authentication
    auth:
      token_expire_minutes: 30
      hash_algorithm: HS256
      min_password_length: 8

    # Service URLs and Configuration
    services:
      project_manager:
        name: project_manager
        url: http://project-manager-service:8001  # Use k8s service names
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      
      developer:
        name: developer
        url: http://developer-service:8002
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      
      ux_designer:
        name: ux_designer
        url: http://ux-designer-service:8003
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      
      tester:
        name: tester
        url: http://tester-service:8004
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      
      code_review:
        name: code_review
        url: http://code-review-service:8005
        timeout: 30
        retry_attempts: 3
        retry_delay: 1

---
apiVersion: v1
kind: Secret
metadata:
  name: cahoots-secrets
type: Opaque
stringData:
  secrets.yaml: |
    # Redis Secrets
    redis:
      password: ${REDIS_PASSWORD}

    # Authentication Secrets
    auth:
      secret_key: ${JWT_SECRET_KEY}

    # External Services
    external:
      github_api_key: ${GITHUB_API_KEY}
      trello_api_key: ${TRELLO_API_KEY}
      trello_api_secret: ${TRELLO_API_SECRET}

---
apiVersion: v1
kind: Secret
metadata:
  name: cahoots-tls
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_CERT_BASE64}
  tls.key: ${TLS_KEY_BASE64} 