apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: cahoots
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cahoots
data:
  POSTGRES_DB: "cahoots"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "cahoots"
  PGDATA: "/var/lib/postgresql/data/pgdata"