apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cahoots-ingress
  namespace: cahoots
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - cahoots.cc
    secretName: cahoots-tls
  rules:
  - host: cahoots.cc
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: master
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-client
            port:
              number: 80