apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: cahoots
spec:
  selector:
    matchLabels:
      app: master
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      serviceAccountName: cahoots-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      imagePullSecrets:
<<<<<<< Updated upstream
      - name: ghcr-auth
=======
      - name: ghcr-pull-secret
      # Add init container to ensure database is ready before starting the main container
>>>>>>> Stashed changes
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done;']
      containers:
      - name: master
        image: ghcr.io/cahoots-org/cahoots-master:latest
<<<<<<< Updated upstream
=======
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        command: ["/bin/sh", "-c", "./start.sh"]
>>>>>>> Stashed changes
        envFrom:
        - configMapRef:
            name: redis-config
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONPATH
          value: "/app"
        - name: REDIS_HOST
          value: redis
        - name: POSTGRES_HOST
          value: db
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SKIP_DB_CHECK
          value: "false"  # Changed to false since we now have an init container
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: cahoots
spec:
  selector:
    app: master
  ports:
  - port: 80
    targetPort: 8000
<<<<<<< Updated upstream
  type: ClusterIP 
=======
  type: ClusterIP
>>>>>>> Stashed changes
