apiVersion: v1
kind: Namespace
metadata:
  name: cahoots
  labels:
    name: cahoots
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cahoots-sa
  namespace: cahoots
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cahoots-role
  namespace: cahoots
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cahoots-role-binding
  namespace: cahoots
subjects:
- kind: ServiceAccount
  name: cahoots-sa
  namespace: cahoots
roleRef:
  kind: Role
  name: cahoots-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: cahoots
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress