apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cahoots
data:
  POSTGRES_DB: cahoots
  POSTGRES_USER: cahoots
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cahoots
type: Opaque
data:
  POSTGRES_PASSWORD: Y2Fob290cw==  # "cahoots" in base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cahoots
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: cahoots
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP 