apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cahoots
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme" # You should replace this with a secure password
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: cahoots
type: kubernetes.io/dockerconfigjson
data:
  # This is a placeholder - you'll need to replace it with your actual GitHub Container Registry credentials
  # You can generate this with: kubectl create secret docker-registry ghcr-pull-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=YOUR_GITHUB_USERNAME \
  #   --docker-password=YOUR_GITHUB_TOKEN \
  #   --docker-email=YOUR_EMAIL \
  #   -o yaml --dry-run=client
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJSRVBMQUNFX1dJVEhfWU9VUl9BQ1RVQUxfQkFTRTY0X0VOQ09ERURfQ1JFREVOVElBTFMifX19