apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: cahoots
spec:
  selector:
    matchLabels:
      app: web-client
  replicas: 1
  template:
    metadata:
      labels:
        app: web-client
    spec:
      imagePullSecrets:
      - name: ghcr-auth
      containers:
      - name: web-client
        image: ghcr.io/cahoots-org/web-client:latest
        env:
        - name: API_URL
          value: "https://cahoots.cc/api"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-client
  namespace: cahoots
spec:
  selector:
    app: web-client
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP 