apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: cahoots
spec:
  selector:
    matchLabels:
      app: web-client
  replicas: 1
  template:
    metadata:
      labels:
        app: web-client
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: web-client
        image: ghcr.io/cahoots-org/cahoots-web-client:latest
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_URL
          value: "http://master"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-client
  namespace: cahoots
spec:
  selector:
    app: web-client
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
