apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: master-service
spec:
  template:
    metadata:
      labels:
        app: master-service
    spec:
      containers:
      - name: master-service
        image: ai-dev-team/master:latest

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pm-service
spec:
  template:
    metadata:
      labels:
        app: pm-service
    spec:
      containers:
      - name: pm-service
        image: ai-dev-team/pm:latest

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-dev-service
  namespace: ai-dev-team
spec:
  template:
    metadata:
      labels:
        app: frontend-dev-service
    spec:
      containers:
      - name: frontend-dev-service
        image: ai-dev-team/developer:latest
        
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend-dev-service
  namespace: ai-dev-team
spec:
  template:
    metadata:
      labels:
        app: backend-dev-service
    spec:
      containers:
      - name: backend-dev-service
        image: ai-dev-team/developer:latest
        env:
        - name: DEVELOPER_FOCUS
          value: "backend"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ux-service
  namespace: ai-dev-team
spec:
  template:
    metadata:
      labels:
        app: ux-service
    spec:
      containers:
      - name: ux-service
        image: ai-dev-team/ux:latest

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tester-service
  namespace: ai-dev-team
spec:
  template:
    metadata:
      labels:
        app: tester-service
    spec:
      containers:
      - name: tester-service
        image: ai-dev-team/tester:latest
