// Import only the specific icons we need
import {
  IconBrain,
  IconRobot,
  IconCode,
  IconGitBranch,
  IconBuildingFactory,
  IconTestPipe,
  IconBug,
  IconServer,
  IconBrandGoogle,
  IconBrandGithub,
  IconPlus,
  IconFolder,
  IconExternalLink,
  IconAlertCircle,
  IconCheck,
  IconInfoCircle,
  IconDashboard,
  IconSettings,
  IconDotsVertical,
} from '@tabler/icons-react';

// Export the icons
export {
  IconBrain,
  IconRobot,
  IconCode,
  IconGitBranch,
  IconBuildingFactory,
  IconTestPipe,
  IconBug,
  IconServer,
  IconBrandGoogle,
  IconBrandGithub,
  IconPlus,
  IconFolder,
  IconExternalLink,
  IconAlertCircle,
  IconCheck,
  IconInfoCircle,
  IconDashboard,
  IconSettings,
  IconDotsVertical,
}; 