---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-dev-team-config
data:
  default.yaml: |
    # Environment
    env: production  # Override for production
    debug: false
    log_level: INFO

    # Redis Configuration
    redis:
      host: redis  # Simple name works in both k8s and docker-compose
      port: 6379
      db: 0
      cluster_mode: false

    # Authentication
    auth:
      token_expire_minutes: 30
      hash_algorithm: HS256
      min_password_length: 8

    # Service URLs and Configuration
    services:
      project_manager:
        name: project_manager
        url: http://pm-service:8000  # Simple service name works in both environments
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      
      developer:
        name: developer
        url: http://developer-service:8000
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      
      ux_designer:
        name: ux_designer
        url: http://ux-service:8000
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      
      tester:
        name: tester
        url: http://tester-service:8000
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      
      code_review:
        name: code_review
        url: http://master-service:8000
        timeout: 30
        retry_attempts: 3
        retry_delay: 1 