apiVersion: v1
kind: ConfigMap
metadata:
  name: cahoots-config
data:
  LOG_LEVEL: "DEBUG"
  REDIS_HOST: "cahoots-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  default.yaml: |
    # Default Configuration
    env: development
    debug: true
    log_level: DEBUG

    # Redis Configuration
    redis:
      host: cahoots-redis
      port: 6379
      db: 0
      client_name: ai_dev_team
      cluster_mode: false
      socket_timeout: 5
      socket_connect_timeout: 2
      max_connections_per_worker: 10
      worker_concurrency: 4
      health_check_interval: 30

    # API Configuration
    api:
      max_request_size_mb: 10
      request_timeout_seconds: 30
      rate_limit:
        requests_per_minute: 60
        burst_size: 10
      allowed_hosts:
        - "*"
      cors_origins:
        - "*"
      version: 0.1.0

    # Service Configuration
    services:
      github:
        name: github
        url: https://api.github.com
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      together:
        name: together
        url: https://api.together.xyz
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
      trello:
        name: trello
        url: https://api.trello.com/1
        timeout: 30
        retry_attempts: 3
        retry_delay: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: cahoots-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  GITHUB_API_KEY: "${GITHUB_API_KEY}"
  TOGETHER_API_KEY: "${TOGETHER_API_KEY}"
  TRELLO_API_KEY: "${TRELLO_API_KEY}"
  TRELLO_API_SECRET: "${TRELLO_API_SECRET}" 