apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-dev-team
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
  - hosts:
    - ai-dev-team.example.com
    secretName: ai-dev-team-tls
  rules:
  - host: ai-dev-team.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-dev-team
            port:
              name: http 