apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cahoots

commonLabels:
  app.kubernetes.io/name: cahoots
  app.kubernetes.io/managed-by: kustomize

resources:
- redis.yaml
- configmap.yaml
- services.yaml
- deployments.yaml
- health-check-configmap.yaml

configMapGenerator:
- name: cahoots-config
  behavior: merge
  literals:
  - REDIS_HOST=cahoots-redis
  - REDIS_PORT=6379
  - REDIS_DB=0
  - LOG_LEVEL=DEBUG 