apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-dev-team

commonLabels:
  app.kubernetes.io/name: ai-dev-team
  app.kubernetes.io/managed-by: kustomize

resources:
- redis.yaml
- configmap.yaml
- services.yaml
- deployments.yaml
- health-check-configmap.yaml

configMapGenerator:
- name: ai-dev-team-config
  behavior: merge
  literals:
  - REDIS_HOST=ai-dev-team-redis
  - REDIS_PORT=6379
  - REDIS_DB=0
  - LOG_LEVEL=DEBUG 