apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: cahoots
spec:
  selector:
    matchLabels:
      app: master
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command: ['sh', '-c', 
          'until pg_isready -h db -p 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: master
        image: ghcr.io/$GITHUB_REPOSITORY_OWNER/cahoots-master:$GITHUB_SHA
        envFrom:
        - configMapRef:
            name: redis-config
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: cahoots
spec:
  selector:
    app: master
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP 