apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-dev-team
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: ai-dev-team
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 14s
    basicAuth:
      username:
        name: ai-dev-team-secrets
        key: PROMETHEUS_BASIC_AUTH_USER
      password:
        name: ai-dev-team-secrets
        key: PROMETHEUS_BASIC_AUTH_PASS
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-metrics
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: redis
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ai-dev-team-alerts
spec:
  groups:
  - name: ai-dev-team
    rules:
    - alert: ServiceDown
      expr: up{app_kubernetes_io_part_of="ai-dev-team"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Service {{ $labels.pod }} is down"
    - alert: HighErrorRate
      expr: |
        rate(http_requests_total{status=~"5..",app_kubernetes_io_part_of="ai-dev-team"}[5m])
        / rate(http_requests_total{app_kubernetes_io_part_of="ai-dev-team"}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate on {{ $labels.pod }}"
    - alert: RedisDown
      expr: up{app="redis"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Redis instance {{ $labels.pod }} is down"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      kubernetes_url "#{ENV['KUBERNETES_URL']}"
      bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
      ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      skip_labels false
      skip_container_metadata false
      skip_namespace_metadata false
      skip_master_url false
    </filter>

    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch-master
      port 9200
      logstash_format true
      logstash_prefix k8s
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever false
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match> 