apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cahoots-network-policy
  namespace: cahoots
spec:
  podSelector:
    matchLabels:
      app: cahoots
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: cahoots
    ports:
    - protocol: TCP
      port: 8000
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: cahoots-redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9090
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-network-policy
  namespace: cahoots
spec:
  podSelector:
    matchLabels:
      app: cahoots-redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: cahoots
    ports:
    - protocol: TCP
      port: 6379 