apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cahoots
data:
  POSTGRES_DB: "cahoots"
  POSTGRES_USER: "cahoots"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cahoots
type: Opaque
data:
  POSTGRES_PASSWORD: "Y2Fob290cy1wYXNzd29yZA==" # cahoots-password in base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cahoots
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "cahoots"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "cahoots"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: cahoots
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP 