apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cahoots
data:
  POSTGRES_DB: "cahoots"
  POSTGRES_USER: "cahoots"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cahoots
type: Opaque
data:
  POSTGRES_PASSWORD: "Y2Fob290cy1wYXNzd29yZA==" # cahoots-password in base64
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: cahoots
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: cahoots
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP 