apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-manager
  namespace: cahoots
spec:
  selector:
    matchLabels:
      app: project-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: project-manager
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: project-manager
        image: ghcr.io/cahoots-org/cahoots-project_manager:latest
        envFrom:
        - configMapRef:
            name: redis-config
        env:
        - name: DATABASE_URL
          value: "postgresql://cahoots:cahoots-password@db:5432/cahoots"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: project-manager
  namespace: cahoots
spec:
  selector:
    app: project-manager
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP 