---
apiVersion: v1
kind: Secret
metadata:
  name: ai-dev-team-secrets
type: Opaque
stringData:
  secrets.yaml: |
    # Redis Secrets
    redis:
      password: ${REDIS_PASSWORD}

    # Authentication Secrets
    auth:
      secret_key: ${JWT_SECRET_KEY}

    # External Services
    external:
      github_api_key: ${GITHUB_API_KEY}
      trello_api_key: ${TRELLO_API_KEY}
      trello_api_secret: ${TRELLO_API_SECRET}

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-dev-team-tls
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_CERT_BASE64}
  tls.key: ${TLS_KEY_BASE64} 