apiVersion: v1
kind: Service
metadata:
  name: cahoots-master
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: cahoots-master
---
apiVersion: v1
kind: Service
metadata:
  name: cahoots-project-manager
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: cahoots-project-manager
---
apiVersion: v1
kind: Service
metadata:
  name: cahoots-developer
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: cahoots-developer
---
apiVersion: v1
kind: Service
metadata:
  name: cahoots-ux-designer
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: cahoots-ux-designer
---
apiVersion: v1
kind: Service
metadata:
  name: cahoots-tester
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: cahoots-tester
---
apiVersion: v1
kind: Service
metadata:
  name: cahoots
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: cahoots-master 