# Developer Agent Configuration
event_subscriptions:
  # Core development events
  story_assigned: handle_story_assignment
  feedback_received: handle_feedback
  review_requested: handle_review_request
  
  # Code-specific events
  code_review_requested: handle_code_review
  test_failed: handle_test_failure
  
  # Collaboration events
  design_completed: handle_design_update
  qa_feedback: handle_qa_feedback
  
  # System events
  system_alert: handle_system_alert
  deployment_status: handle_deployment_status

# AI configuration
ai:
  provider: openai
  models:
    default: gpt-4
    fallback: gpt-3.5-turbo
    embeddings: text-embedding-3-small
  settings:
    temperature: 0.7
    max_tokens: 4096

# Agent-specific settings
settings:
  workspace_dir: /app/workspace
  auto_commit: true
  review_batch_size: 5
  max_concurrent_tasks: 3
  log_level: INFO
  health_check_interval: 30
  retry_attempts: 3
  timeout: 60
  metrics_enabled: true

name: developer
description: Developer agent for handling development tasks
role: developer
version: 0.1.0

communication:
  event_bus:
    host: localhost
    port: 5672
    channels:
      - development
      - code_review
      - testing

capabilities:
  - code_generation
  - code_review
  - testing
  - debugging
  - documentation

security:
  requires_auth: true
  allowed_roles:
    - developer
    - admin

resources:
  memory_limit: 1024Mi
  cpu_limit: 1.0
  storage_limit: 1Gi 