# Project Manager Agent Configuration
event_subscriptions:
  # System events
  system_alert: handle_system_alert
  health_check: handle_health_check
  config_update: handle_config_update
  metrics_request: handle_metrics_request
  # Project management events
  task_created: handle_task_created
  task_updated: handle_task_updated
  task_completed: handle_task_completed
  sprint_planning: handle_sprint_planning
  team_status: handle_team_status

# AI configuration
ai:
  provider: openai
  models:
    default: gpt-3.5-turbo
    fallback: gpt-3.5-turbo-16k
    embeddings: text-embedding-3-small
  settings:
    temperature: 0.7
    max_tokens: 2048

# Agent settings
settings:
  log_level: INFO
  metrics_enabled: true
  health_check_interval: 60
  retry_attempts: 3
  timeout: 30
  project_methodology: agile
  sprint_duration_days: 14
  task_estimation_method: story_points
  priority_levels:
    - critical
    - high
    - medium
    - low