# UX Designer Agent Configuration
name: ux-designer
description: UX designer agent for user interface and experience design
role: ux-designer
version: 0.1.0

event_subscriptions:
  # System events
  system_alert: handle_system_alert
  health_check: handle_health_check
  config_update: handle_config_update
  metrics_request: handle_metrics_request
  # UX specific events
  design_requested: handle_design_request
  feedback_received: handle_feedback
  prototype_requested: handle_prototype_request
  usability_test: handle_usability_test

# AI configuration
ai:
  provider: openai
  models:
    default: gpt-4
    fallback: gpt-3.5-turbo
    embeddings: text-embedding-3-small
  settings:
    temperature: 0.7
    max_tokens: 4096

# Agent settings
settings:
  log_level: INFO
  metrics_enabled: true
  health_check_interval: 30
  retry_attempts: 3
  timeout: 60
  design_system: material
  accessibility_standard: WCAG2.1
  color_contrast_threshold: 4.5

communication:
  event_bus:
    host: localhost
    port: 5672
    channels:
      - design
      - feedback
      - prototypes

capabilities:
  - ui_design
  - ux_research
  - prototyping
  - usability_testing

security:
  requires_auth: true
  allowed_roles:
    - admin
    - designer

resources:
  memory_limit: 1024Mi
  cpu_limit: 1.0
  storage_limit: 1Gi 